Rename sr:stage:1023889.json to srstage1023889.json
remove the colon because file name can have it on windows, was causing error when pulling or changing branch.

error: invalid path 'data/sr:stage:1023889.json'